### ISSUE TITLE
Services non voulus après stack:init

### ISSUE THREAD

**Issue by nicolas43000** [kiboko-labs/docker-images#7]
Quand je fais la commande `kloud stack:init` avec : 
- blackfire = non
- xdebug = non

3 services en trop sont créés dans `docker-compose.yml` qui sont : 
- fpm-xdebug
- sh-xdebug
- blackfire

**Comment by gplanchat** [comment]
Disponible dans la version [1.0.2](https://github.com/kiboko-labs/docker-images/releases/tag/1.0.2)
