### ISSUE TITLE
add psql in sh image 

### ISSUE THREAD

**Issue by programgames** [kiboko-labs/docker-images#8]
The psql utility should be available in the sh image.
Example: ( kiboko/php:7.2-cli-blackfire-orocommerce-ee-3.1-postgresql )
Because some php class , like https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/TestFrameworkBundle/Behat/Isolation/UnixPgsqlIsolator.php

start a psql process in the container

**Comment by gplanchat** [comment]
Fixed in 1.0.4
